### ISSUE TITLE
运行 tg-signer run 提示如下  请问是我操作的问题吗还是哪里没配置对 还请大佬指点

### ISSUE THREAD

**Issue by Even1f** [amchii/tg-signer#5]
root@VMHKBVOUEJUH:~# tg-signer run
Traceback (most recent call last):
  File "/usr/local/bin/tg-signer", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/tg_signer/__main__.py", line 2, in cli
    from .signer import app, main
  File "/usr/local/lib/python3.8/dist-packages/tg_signer/signer.py", line 90, in <module>
    class SignConfig:
  File "/usr/local/lib/python3.8/dist-packages/tg_signer/signer.py", line 91, in SignConfig
    chats: list[SignChat]
TypeError: 'type' object is not subscriptable

**Comment by amchii** [comment]
使用Python3.9及以上，下次升级会支持Python3.8。

**Comment by amchii** [comment]
0.2.0支持Python3.8了
