### ISSUE TITLE
pyrogram运行错误

### ISSUE THREAD

**Issue by Suuperfishy** [amchii/tg-signer#7]
[INFO] [pyrogram.session.auth] 2024-09-28 00:14:21,308 auth.py 82 Start creating a new auth key on DC2
[INFO] [pyrogram.session.auth] 2024-09-28 00:14:21,309 auth.py 269 Retrying due to AttributeError: module 'socks' has no attribute ''
Traceback (most recent call last):
  File "D:\program\tg-signer\tg_signer\signer.py", line 354, in <module>
    app.run(main())
  File "C:\Users\Suupe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyrogram\methods\utilities\run.py", line 77, in run
    run(coroutine)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\program\tg-signer\tg_signer\signer.py", line 337, in main
    return await signer.login()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\program\tg-signer\tg_signer\signer.py", line 224, in login
    async with app:
               ^^^
  File "D:\program\tg-signer\tg_signer\signer.py", line 42, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Suupe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Suupe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\Suupe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyrogram\client.py", line 637, in load_session
    await Auth(
  File "C:\Users\Suupe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyrogram\session\auth.py", line 281, in create
    await self.connection.close()
  File "C:\Users\Suupe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyrogram\connection\connection.py", line 65, in close
    await self.protocol.close()
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

才疏学浅，没能定位到错误...pip把依赖库都重装过了...另外，恳请大佬打个docker包

**Comment by Suuperfishy** [comment]
此外，使用python直接命令行python signer.py run task_name程序读不到任务名，exe似乎也不行

**Comment by amchii** [comment]
你好，我暂时没用Windows测试过，Docker的话我等有空弄一个吧

**Comment by amchii** [comment]
有热心用户提供了docker部署，参考：
https://linux.do/t/topic/91604/90
